# -*- coding: utf-8 -*-
"""NLP Libraries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXAeM79UqMxQXRuKJAizuJLWLbeco8LM
"""

!pip install gensim

from gensim.models import Word2Vec
sentences = [['natural', 'language', 'processing', 'nlp', 'field', 'combine', 'computer', 'science', 'artificial', 'intelligence', 'language', 'study', 'help', 'computer', 'understand', 'process', 'create', 'human', 'language', 'way', 'make', 'sense', 'useful', 'growing', 'amount', 'text', 'data', 'social', 'medium', 'website', 'source', 'nlp', 'becoming', 'key', 'tool', 'gain', 'insight', 'automate', 'task', 'like', 'analyzing', 'text', 'translating', 'language']]
model = Word2Vec(sentences, vector_size=50, window=3, min_count=1, workers=4)
print(model.wv['natural'])

for token in sentences:
  print(model.wv[token])

